ALTER TABLE BZ_CODE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS BZ_CODE;

ALTER TABLE BZ_SYS_RSTYPE DROP PRIMARY KEY;
DROP TABLE IF EXISTS BZ_SYS_RSTYPE;

ALTER TABLE BZ_SYS_DEFINED DROP PRIMARY KEY;
DROP TABLE IF EXISTS BZ_SYS_DEFINED;

ALTER TABLE BZ_CLUSTERNODE DROP PRIMARY KEY;
DROP TABLE IF EXISTS BZ_CLUSTERNODE;

ALTER TABLE ATT_TYPE DROP PRIMARY KEY;
DROP TABLE IF EXISTS ATT_TYPE;

ALTER TABLE BZ_CODESORT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS BZ_CODESORT;

ALTER TABLE BZ_DATA_ELE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS BZ_DATA_ELE;

ALTER TABLE BZ_DATA_ELE_SORT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS BZ_DATA_ELE_SORT;

ALTER TABLE IM_MESSAGE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS IM_MESSAGE;

ALTER TABLE IM_MESSAGE_ARCHIVE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS IM_MESSAGE_ARCHIVE;

ALTER TABLE IM_MESSAGE_HISTORY
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS IM_MESSAGE_HISTORY;

ALTER TABLE PUB_ACCOUNT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ACCOUNT;

ALTER TABLE PUB_ACCOUNT_TYPE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ACCOUNT_TYPE;

ALTER TABLE PUB_ADMIN
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ADMIN;

ALTER TABLE PUB_ADMIN_APP_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ADMIN_APP_RELA;

ALTER TABLE PUB_ADMIN_ORGAN_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ADMIN_ORGAN_RELA;

ALTER TABLE PUB_ADMIN_ROLE_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ADMIN_ROLE_RELA;

ALTER TABLE PUB_APP
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_APP;

ALTER TABLE PUB_APP_CONTEXT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_APP_CONTEXT;

ALTER TABLE PUB_APP_NAV
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_APP_NAV;

ALTER TABLE PUB_AUDIT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT;

ALTER TABLE PUB_AUDIT_ACT_TYPE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT_ACT_TYPE;

ALTER TABLE PUB_AUDIT_ARCHIVE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT_ARCHIVE;

ALTER TABLE PUB_AUDIT_ARCHIVE_SET
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT_ARCHIVE_SET;

ALTER TABLE PUB_AUDIT_CLEAR_LOG
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT_CLEAR_LOG;

ALTER TABLE PUB_AUDIT_SYSTEM
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT_SYSTEM;

ALTER TABLE PUB_AUDIT_SYSTEM_ARCHIVE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_AUDIT_SYSTEM_ARCHIVE;

ALTER TABLE PUB_CLICK_COUNT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_CLICK_COUNT;

ALTER TABLE PUB_CLICK_COUNT_DETAIL
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_CLICK_COUNT_DETAIL;

ALTER TABLE PUB_COUNT_CATALOG
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_COUNT_CATALOG;

ALTER TABLE PUB_EXT_INFO
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_EXT_INFO;

ALTER TABLE PUB_LOG
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_LOG;

ALTER TABLE PUB_LOG_SYSTEM
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_LOG_SYSTEM;

ALTER TABLE PUB_MENU
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_MENU;

ALTER TABLE PUB_MODULE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_MODULE;

ALTER TABLE PUB_ORGAN
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ORGAN;

ALTER TABLE PUB_ORGAN_TYPE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ORGAN_TYPE;

ALTER TABLE PUB_ORG_APP_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ORG_APP_RELA;

ALTER TABLE PUB_ORG_GRADE_ROLE_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ORG_GRADE_ROLE_RELA;

ALTER TABLE PUB_ORG_PERSON_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ORG_PERSON_RELA;

ALTER TABLE PUB_ORG_ROLE_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ORG_ROLE_RELA;

ALTER TABLE PUB_PERSON
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_PERSON;

ALTER TABLE PUB_PERSON_APP_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_PERSON_APP_RELA;

ALTER TABLE PUB_PERSON_EXT
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_PERSON_EXT;

ALTER TABLE PUB_PERSON_ROLE_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_PERSON_ROLE_RELA;

ALTER TABLE PUB_POLICY_ACCOUNT_PWD
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POLICY_ACCOUNT_PWD;

ALTER TABLE PUB_POLICY_ACCOUNT_PWD_RULE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POLICY_ACCOUNT_PWD_RULE;

ALTER TABLE PUB_POLICY_ACCOUNT_UNLOCK
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POLICY_ACCOUNT_UNLOCK;

ALTER TABLE PUB_POLICY_IP
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POLICY_IP;

ALTER TABLE PUB_POSITION
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POSITION;

ALTER TABLE PUB_POSITION_GRADE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POSITION_GRADE;

ALTER TABLE PUB_POSITION_ROLE_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_POSITION_ROLE_RELA;

ALTER TABLE PUB_PROP_EXTEND
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_PROP_EXTEND;

ALTER TABLE PUB_PROP_EXTEND_DATA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_PROP_EXTEND_DATA;

ALTER TABLE PUB_RESOURCE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_RESOURCE;

ALTER TABLE PUB_ROLE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ROLE;

ALTER TABLE PUB_ROLE_GROUP
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ROLE_GROUP;

ALTER TABLE PUB_ROLE_GROUP_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ROLE_GROUP_RELA;

ALTER TABLE PUB_ROLE_MODULE_RELA
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ROLE_MODULE_RELA;

ALTER TABLE PUB_ROLE_RESOURCE
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_ROLE_RESOURCE;

ALTER TABLE PUB_SCHEDULE_TASK
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SCHEDULE_TASK;

ALTER TABLE PUB_SECURITY_POLICY
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SECURITY_POLICY;

ALTER TABLE PUB_SYNC_CONFIG
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_CONFIG;

ALTER TABLE PUB_SYNC_IMPL_PARAM
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_IMPL_PARAM;

ALTER TABLE PUB_SYNC_RECORD
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_RECORD;

ALTER TABLE PUB_SYNC_RECORD_HISTORY
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_RECORD_HISTORY;

ALTER TABLE PUB_SYNC_RECORD_STATUS
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_RECORD_STATUS;

ALTER TABLE PUB_SYNC_RECORD_STATUS_HISTORY
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_RECORD_STATUS_HISTORY;

ALTER TABLE PUB_SYNC_TARGET
   DROP PRIMARY KEY;

DROP TABLE IF EXISTS PUB_SYNC_TARGET;

drop table if exists WB_ROLE;
drop table if exists WB_FUN;
drop table if exists WB_ROLE_FUN;
drop table if exists WB_USER;
drop table if exists WB_SYSTEM;
drop table if exists WB_UHHU;
drop table if exists WB_UHHU_IP;
drop table if exists WB_ORGAN_LOGIN;
drop table if exists WB_SYS_ORGAN;