

ALTER TABLE PUB_ACCOUNT ADD CONSTRAINT FK_PUB_ACC_R_P FOREIGN KEY (PERSON_ID)
      REFERENCES PUB_PERSON (PERSON_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ADMIN_ORGAN_RELA ADD CONSTRAINT FK_ADM_ORG_R_A FOREIGN KEY (PUB_ID)
      REFERENCES PUB_ADMIN (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ADMIN_ORGAN_RELA ADD CONSTRAINT FK_PUB_ADM_R_ORG FOREIGN KEY (ID)
      REFERENCES PUB_ORGAN (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_APP_CONTEXT ADD CONSTRAINT FK_REFERENCE_21 FOREIGN KEY (APP_ID)
      REFERENCES PUB_APP (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_CLICK_COUNT ADD CONSTRAINT FK_PUB_CLIC_R_T FOREIGN KEY (PAGE_ID)
      REFERENCES PUB_COUNT_CATALOG (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_CLICK_COUNT_DETAIL ADD CONSTRAINT FK_PUB_CLK_DL_R_T FOREIGN KEY (PAGE_ID)
      REFERENCES PUB_COUNT_CATALOG (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_MENU ADD CONSTRAINT FK_PUB_MENU_R_NV FOREIGN KEY (NAV_ID)
      REFERENCES PUB_APP_NAV (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_MODULE ADD CONSTRAINT FK_PUB_MODU_R_APP FOREIGN KEY (APP_ID)
      REFERENCES PUB_APP (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ORGAN ADD CONSTRAINT FK_PUB_ORGA_R_T FOREIGN KEY (PUB_ID)
      REFERENCES PUB_ORGAN_TYPE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ORG_PERSON_RELA ADD CONSTRAINT FK_PUB_ORG_P_R_O FOREIGN KEY (ORG_ID)
      REFERENCES PUB_ORGAN (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ORG_PERSON_RELA ADD CONSTRAINT FK_PUB_ORG_P_R_P FOREIGN KEY (PERSON_ID)
      REFERENCES PUB_PERSON (PERSON_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ORG_PERSON_RELA ADD CONSTRAINT FK_PUB_ORG_P_R_PO FOREIGN KEY (POST)
      REFERENCES PUB_POSITION (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ORG_ROLE_RELA ADD CONSTRAINT FK_PUB_ORG_ROL_R FOREIGN KEY (ROLE_ID)
      REFERENCES PUB_ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_PERSON ADD CONSTRAINT FK_PUB_PER_R_PO_L FOREIGN KEY (POST_LEVEL)
      REFERENCES PUB_POSITION_GRADE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_PERSON_EXT ADD CONSTRAINT FK_PUB_PEXT_R_P FOREIGN KEY (PERSON_ID)
      REFERENCES PUB_PERSON (PERSON_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_PERSON_ROLE_RELA ADD CONSTRAINT FK_PUB_PER_ROL_R FOREIGN KEY (ROLE_ID)
      REFERENCES PUB_ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_PROP_EXTEND_DATA ADD CONSTRAINT FK_REFERENCE_19 FOREIGN KEY (PROP_ID)
      REFERENCES PUB_PROP_EXTEND (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_RESOURCE ADD CONSTRAINT FK_PUB_RES_R_MD FOREIGN KEY (MODULE_ID)
      REFERENCES PUB_MODULE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ROLE_GROUP_RELA ADD CONSTRAINT FK_PUB_ROLE_GP_R FOREIGN KEY (ROLE_ID)
      REFERENCES PUB_ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ROLE_GROUP_RELA ADD CONSTRAINT FK_PUB_ROLE_R_GP FOREIGN KEY (GROUP_ID)
      REFERENCES PUB_ROLE_GROUP (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ROLE_MODULE_RELA ADD CONSTRAINT FK_PUB_ROL_R_MOD FOREIGN KEY (MODULE_ID)
      REFERENCES PUB_MODULE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ROLE_MODULE_RELA ADD CONSTRAINT FK_REFERENCE_20 FOREIGN KEY (ROLE_ID)
      REFERENCES PUB_ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PUB_ROLE_RESOURCE ADD CONSTRAINT FK_PUB_ROL_R_RES FOREIGN KEY (RES_ID)
      REFERENCES PUB_RESOURCE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE BZ_DATA_ELE ADD CONSTRAINT FK_BZ_DATA_R_T FOREIGN KEY (ELE_SORT_ID)
      REFERENCES BZ_DATA_ELE_SORT (ELE_SORT_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;      